-- CREATE OR REFRESH STREAMING TABLE silver_customers (
--   CONSTRAINT customer_id_not_null
--     EXPECT (customer_id IS NOT NULL) ON VIOLATION DROP ROW,

--   CONSTRAINT customer_unique_id_not_null
--     EXPECT (customer_unique_id IS NOT NULL) ON VIOLATION DROP ROW
-- )
-- AS
-- SELECT 
--   TRIM(customer_id) AS customer_id,
--   TRIM(customer_unique_id) AS customer_unique_id,
--   CAST(TRIM(customer_zip_code_prefix) AS INT) AS customer_zip_code_prefix,
--   TRIM(INITCAP(customer_city)) AS customer_city,
--   TRIM(customer_state) AS customer_state,
--   CURRENT_TIMESTAMP() AS processed_time,
--   '1.0' AS silver_layer_version
-- FROM STREAM bronze_customers;
